**Table of contents**<a id='toc0_'></a>    
- [File Handling](#toc1_)    
  - [Syntax](#toc1_1_)    
  - [How to Open a File](#toc1_2_)    
  - [Read Lines](#toc1_3_)    
  - [Write to an Existing File](#toc1_4_)    
  - [Create a New File](#toc1_5_)    
  - [Delete a File](#toc1_6_)    
- [Introduction to Numpy](#toc2_)    
  - [Installation of Numpy](#toc2_1_)    
  - [Numpy Arrays](#toc2_2_)    
  - [Attributes of Arrays](#toc2_3_)    
  - [Slicing of Arrays](#toc2_4_)    
  - [Quick Note on Array Indexing](#toc2_5_)    
  - [Numpy Array Indexing](#toc2_6_)    
  - [Reshaping of Arrays](#toc2_7_)    
  - [Joining and Splitting of Arrays](#toc2_8_)    
  - [Numpy Operations](#toc2_9_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# <a id='toc1_'></a>[File Handling](#toc0_)

File handling is an essential aspect of programming that allows us to work with files on a computer. Python provides built-in functions and methods to handle file operations. In this notebook, we will explore various file handling concepts.

## <a id='toc1_1_'></a>[Syntax](#toc0_)

To perform file operations in Python, we use the following basic syntax:

```python
# Opening a file
file = open(filename, mode)

# Performing file operations
# ...

# Closing the file
file.close()
```

## <a id='toc1_2_'></a>[How to Open a File](#toc0_)

To open a file in Python, we use the `open()` function. The function takes two arguments: the `filename` (a string representing the file name or path) and the `mode` (a string indicating the purpose of opening the file).

Let's see an example of opening a text file in read mode:

In [1]:
!echo "Sample File" > example.txt

In [3]:
file = open('example.txt', 'r')
print(file) # TextIOWrapper object
file.close()

<_io.TextIOWrapper name='example.txt' mode='r' encoding='UTF-8'>


## <a id='toc1_3_'></a>[Read Lines](#toc0_)

Once a file is opened, we can read its contents using various methods. One common method is `readlines()`, which reads all the lines of a file and returns them as a list of strings.

Let's see an example of reading the lines from a file and printing them:

In [8]:
!echo -e "Sample File\nThis is line # 2" > example.txt

In [9]:
file = open('example.txt', 'r')
lines = file.readlines()
file.close()

for line in lines:
    print(line)

Sample File

This is line # 2



## <a id='toc1_4_'></a>[Write to an Existing File](#toc0_)

To write to an existing file, we open the file in write mode (`'w'`) or append mode (`'a'`), and then use the `write()` method to write the desired content.

Let's see an example of writing to an existing file:

In [10]:
file = open('example.txt', 'w')
file.write('Hello, World!')
file.close()

## <a id='toc1_5_'></a>[Create a New File](#toc0_)

To create a new file, we can open a file in write mode (`'w'`) or use the `open()` function with `'x'` mode, which creates a new file for writing.

Let's see an example of creating a new file and writing to it:

In [18]:
file = open('new_file.txt', 'x')
file.write('This is a new file.')
#
file.close()
_ = !cat new_file.txt
print(_)

['This is a new file.']


## <a id='toc1_6_'></a>[Delete a File](#toc0_)

To delete a file, we can use the `os.remove()` function from the `os` module.

Let's see an example of deleting a file:

In [22]:
import os
file_path = 'file_to_delete.txt'
os.remove(file_path)

# <a id='toc2_'></a>[Introduction to Numpy](#toc0_)

Numpy is a powerful library in Python for numerical computations. It provides support for large, multi-dimensional arrays and matrices, along with a collection of functions to operate on these arrays efficiently. This section introduces the basic concepts and functionalities of Numpy.


## <a id='toc2_1_'></a>[Installation of Numpy](#toc0_)

Before using Numpy, you need to install it. You can install Numpy using the following command:

```python
!pip install numpy
```

Once installed, you can import the Numpy module using the following import statement:

In [23]:

import numpy as np

## <a id='toc2_2_'></a>[Numpy Arrays](#toc0_)

Numpy arrays are the fundamental data structure in Numpy. They are similar to Python lists but can store homogeneous data and support a variety of operations on the data. Numpy arrays can have one or more dimensions.

Here is an example of creating a Numpy array:

In [24]:
import numpy as np

# Create a 1-dimensional Numpy array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

# Create a 2-dimensional Numpy array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## <a id='toc2_3_'></a>[Attributes of Arrays](#toc0_)

Arrays in NumPy have various attributes that provide useful information about the array. Some commonly used attributes include:

- `ndarray.shape`: Returns the dimensions of the array.
- `ndarray.size`: Returns the total number of elements in the array.
- `ndarray.dtype`: Returns the data type of the elements in the array.
- `ndarray.itemsize`: Returns the size (in bytes) of each element in the array.
- `ndarray.nbytes`: Returns the total size (in bytes) of the array.

Let's see some examples of using these attributes:


In [ ]:
import numpy as np

# Create a 2-dimensional array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Shape of the array
print(arr.shape)  # Output: (2, 3)

# Total number of elements
print(arr.size)  # Output: 6

# Data type of the elements
print(arr.dtype)  # Output: int64

# Size of each element in bytes
print(arr.itemsize)  # Output: 8

# Total size of the array in bytes
print(arr.nbytes)  # Output: 48


## <a id='toc2_5_'></a>[Quick Note on Array Indexing](#toc0_)

In Numpy, array indexing is similar to Python lists. The index of the first element is 0, the index of the second element is 1, and so on. You can also use negative indexing to "access" elements from the end of the array.

Here are a few examples of array indexing in Numpy:

In [25]:
import numpy as np

# Create a 1-dimensional Numpy array
arr = np.array([1, 2, 3, 4, 5])

# Accessing individual elements
print(arr[0])  # Output: 1
print(arr[2])  # Output: 3
print(arr[-1])  # Output: 5

# Slicing the array
print(arr[1:4])  # Output: [2, 3, 4]
print(arr[:3])  # Output: [1, 2, 3]
print(arr[2:])  # Output: [3, 4, 5]

1
3
5
[2 3 4]
[1 2 3]
[3 4 5]


## <a id='toc2_6_'></a>[Numpy Array Indexing](#toc0_)

Numpy provides powerful indexing capabilities to access and modify elements of arrays based on certain conditions or boolean arrays. It allows for advanced slicing, masking, and fancy indexing.

Here is an example of Numpy array indexing:

In [26]:
import numpy as np

# Create a 1-dimensional Numpy array
arr = np.array([1, 2, 3, 4, 5])

# Boolean indexing
mask = arr > 2
print(arr[mask])  # Output: [3, 4, 5]

# Fancy indexing
indices = [0, 2, 4]
print(arr[indices])  # Output: [1, 3, 5]

[3 4 5]
[1 3 5]


## <a id='toc2_4_'></a>[Slicing of Arrays](#toc0_)

Slicing allows us to access subarrays within a larger array. It provides a powerful way to extract portions of arrays and manipulate them independently. Slicing in NumPy follows the syntax: `start:stop:step`, where `start` is the starting index, `stop` is the stopping index (exclusive), and `step` is the step size between elements.

Let's see some examples of slicing an array:


In [ ]:
import numpy as np

# Create a 1-dimensional array
arr = np.array([1, 2, 3, 4, 5])

# Get a subarray from index 1 to 3 (exclusive)
print(arr[1:3])  # Output: [2, 3]

# Get every second element
print(arr[::2])  # Output: [1, 3, 5]

# Reverse the array
print(arr[::-1])  # Output: [5, 4, 3, 2, 1]


## <a id='toc2_7_'></a>[Reshaping of Arrays](#toc0_)

Reshaping allows us to change the shape of an array without changing its data. The `reshape()` function in NumPy can be used to reshape an array into a different shape. It takes a tuple as the argument, specifying the new shape of the array.

Let's see an example of reshaping an array:


In [2]:
import numpy as np

# Create a 1-dimensional array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
new_arr = arr.reshape((2, 3))

# Print the reshaped array
print(new_arr)


[[1 2 3]
 [4 5 6]]


## <a id='toc2_8_'></a>[Joining and Splitting of Arrays](#toc0_)

NumPy provides functions to join multiple arrays into one and split a single array into multiple smaller arrays.

The `np.concatenate()` function can be used to join arrays along a specified axis. The `np.split()` function can be used to split an array into multiple subarrays of equal size.

Let's see some examples of joining and splitting arrays:


In [3]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Join the arrays along the first axis (vertical stack)
result = np.concatenate((arr1, arr2), axis=0)
print(result)  # Output: [1, 2, 3, 4, 5, 6]

# Split the array into three subarrays
subarrays = np.split(result, 3)
print(subarrays)  # Output: [array([1, 2]), array([3, 4]), array([5, 6])]


[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


## <a id='toc2_9_'></a>[Numpy Operations](#toc0_)

Numpy provides a wide range of mathematical and logical functions to perform operations on arrays efficiently. These functions can be used for element-wise operations, array-wise operations, and other mathematical computations.

Here are a few examples of Numpy operations:

In [4]:
import numpy as np

# Create a 1-dimensional Numpy array
arr = np.array([1, 2, 3, 4, 5])

# Element-wise operations
print(arr + 2)  # Output: [3, 4, 5, 6, 7]
print(arr * 3)  # Output: [3, 6, 9, 12, 15]

# Array-wise operations
print(np.sum(arr))  # Output: 15
print(np.mean(arr))  # Output: 3.0

# Other mathematical computations
print(np.sqrt(arr))  # Output: [1.0, 1.41421356, 1.73205081, 2.0, 2.23606798]

[3 4 5 6 7]
[ 3  6  9 12 15]
15
3.0
[1.         1.41421356 1.73205081 2.         2.23606798]


> ### <a id='toc2_6_'></a>[Exercises](#toc0_)

>1. Create a Numpy array containing the numbers from 1 to 10 and print it.
>2. Square each element in the array from exercise 1 and print the result.
>3. Find the sum of all elements in the array from exercise 1.
>4. Create a 2-dimensional Numpy array with shape (3, 3) containing random numbers between 0 and 1.
>5. Reshape the array from exercise 4 to shape (1, 9).
>6. Compute the mean of each row in the reshaped array from exercise 5.
